### ISSUE TITLE
Create draft charter

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-CG-Charter#1]
Template kindly provide by Doug Schepers: http://w3c.github.io/charter-drafts/charter-template.html

**Comment by Malvoz** [comment]
I understand this isn't on top of priorities but https://github.com/w3c/charter-drafts says:

> For W3C Community Groups, please start from the [CG charter template](https://github.com/w3c/cg-charter).

**Comment by prushforth** [comment]
@Malvoz I copied that template into this repository as index.html.  Unsure if that's ideal, but we can discuss via issues / pull requests.  Thanks!

**Comment by Malvoz** [comment]
Has there been an agreement, or is there otherwise an intention (with moving to maps4html.org) to have _all_ the deliverables available under that domain? If not, we could convert the HTML to markdown and just refer to this repo for the charter?

**Comment by prushforth** [comment]
Linking maps4html.org to the github.io for the organization was a low-friction way to create a single point of entry / homepage for the group that we control.  

I have no problem with making the file into markdown if you think that is good enough.  I guess it can still be linked to.

**Comment by Malvoz** [comment]
Draft charter was created in https://github.com/Maps4HTML/Maps4HTML-CG-Charter/pull/2/commits/2560232ea0e29f77954885c923038844e251facf, closing.
